name: Build and publish Docker
on:
  push:
    branches: main
jobs:

  flake8_lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: latest
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F401"
          exclude: "src/ignoreme.py"
          max-line-length: "100"
          path: "src"
          plugins: "flake8-bugbear==22.1.11 flake8-black"


          
  snyk_test:
    name: Snyk test
    needs: [flake8_lint]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Run Snyk to check for vulnerabilities
      working-directory: ${{github.workspace}}/src
      run: |
        pip install -r requirements.txt
        npm install -g snyk
        snyk auth ${{secrets.SNYK_TOKEN}}
        snyk test
        
  sonnar_cloud_test:
    name: Sonnar cloud test
    needs: [flake8_lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: ["snyk_test","sonnar_cloud_test"]
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
      
      - name: Build and push Docker image
        run: |
            docker build -t "classwork1" .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'classwork1'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


      - name: Tag an image
        run: docker tag classwork1 kzah/devops_classwork1:version1.0
        
      - name: Push an image to DockerHub
        run: docker push kzah/devops_classwork1:version1.0
