name: Build and publish Docker
on:
  push:
    #branches: main
jobs:

  check_makrdown:
    name: Check makrdown files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .

  editorconfig:
    name: EditorConfig Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  flake8_lint:
    name: Check code style & lint with flake8
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: py-actions/flake8@v2

  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
          architecture: x64
      - name: Install requirements
        run: pip3 install -r src/requirements.txt
      - name: Execute Unit Tests
        run: python3 -m unittest src/app_test.py

  snyk_test:
    name: Snyk test
    runs-on: ubuntu-latest
    needs: ["flake8_lint", "check_makrdown", "editorconfig", "unit_test"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Snyk to check for vulnerabilities
      working-directory: ${{github.workspace}}/src
      run: |
        pip install -r requirements.txt
        npm install -g snyk
        snyk auth ${{secrets.SNYK_TOKEN}}
        snyk test

  sonnar_cloud_test:
    name: Sonnar cloud test
    runs-on: ubuntu-latest
    needs: ["flake8_lint", "check_makrdown", "editorconfig", "unit_test"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: ["snyk_test","sonnar_cloud_test"]
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build and push Docker image
        run: |
            docker build -t "classwork1" .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'classwork1'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


      - name: Tag an image
        run: docker tag classwork1 kzah/devops_classwork1:version1.0

      - name: Push an image to DockerHub
        run: docker push kzah/devops_classwork1:version1.0
